### ISSUE TITLE
Order of chapters in the Integration document

### ISSUE THREAD

**Issue by ujos** [OleksandrKvl/sbepp#46]
When I did read the Integration document, I've made the first part of it only ("Compiling schema on-the-fly using your build system"). The instruction is long but it works. Once I've made my project compiling I've skipped the rest of that document.

Yesterday when I investigated how to use the sbepp as a Git submodule, I've found a great CMake helper `sbeppc_compile_schema` and surprisingly I've found the description of that CMake command in the Integration document at the bottom.

I believe would be better to mention that command before you explain how to _compile the schema on-the-fly_.

Otherwise it is like two sappers reading the manual how to deactivate the bomb:

First: Cut the red cord
Second: Ok, done
First: ... after you cut the green one.

**Comment by OleksandrKvl** [comment]
Done :)
