### ISSUE TITLE
unresolved external symbol "unsigned char __cdecl sbepp::detail::byteswap<unsigned char>(unsigned char)"

### ISSUE THREAD

**Issue by ujos** [OleksandrKvl/sbepp#69]
When I build my application based on sbepp v1.3.0 with Visual Studio 2019/2022, I get a link time error:

```
error LNK2001: unresolved external symbol "unsigned char __cdecl sbepp::detail::byteswap<unsigned char>(unsigned char)" (??$byteswap@E@detail@sbepp@@YAEE@Z)
```

Looks like the problem is caused by the following declaration without the definition:

`sbepp\sbepp.hpp:(464)`
```cpp

// because `if((E == endian::native) || (sizeof(T) == 1))` is not a constexpr-if
// this function has to be declared for single byte types even if it will never
// be used
template<typename T>
T byteswap(T) noexcept;
```

g++ 11/12 compiles the code just fine.

Please let me know if you need a full source code to reproduce the issue.

**Comment by OleksandrKvl** [comment]
Interesting, seems the issue is in this section: https://github.com/OleksandrKvl/sbepp/blob/main/sbepp/src/sbepp/sbepp.hpp#L569-L576. MSVC somehow can't figure out from that if-condition that `byteswap` is never used for single-byte types and that it's always known at compile-time. One solution might be to define that function, although it's never be used. I will think if there's a better way.

**Comment by ujos** [comment]
Try constexpr:

```cpp
    if constexpr((E != endian::native) && (sizeof(T) != 1))
    {
        value = from_unsigned<T>{}(byteswap(to_unsigned(value)));
    }
```

**Comment by OleksandrKvl** [comment]
It will work for C++17 but not for C++11/14.

**Comment by OleksandrKvl** [comment]
Can you please check if the fix from PR works for you? I don't have access to MSVC compiler at the moment.

**Comment by ujos** [comment]
As far as you have the template specialization for the 1-byte variables, do you still need that if inside the `set_primitive`?

**Comment by OleksandrKvl** [comment]
Removing `sizeof(T) == 1` part from `if((E == endian::native) || (sizeof(T) == 1))` is possible but if we do so, we will call `from_unsigned<T>{}(byteswap(to_unsigned(res)));` part even for single-byte types. That's essentially a no-op but it will  instantiate `byteswap`, `to_unsigned` and `from_unsigned` to do nothing so I'm not sure it's a good idea.

**Comment by ujos** [comment]
Maybe better then to specialize the `set_primitive` / `get_primitive` functions.

**Comment by ujos** [comment]
Actually two specializations are needed:

```cpp
#include <type_traits>
#include <cstring>

enum endianness
{
    native,
    little,
    big,
};

constexpr auto NativeEndianness = endianness::little;

void reverse_copy(void*, void const*, size_t) {}

template<endianness E, typename T>
typename std::enable_if<E == NativeEndianness || sizeof(T) == 1>::type set_primitive(void* addr, T v)
{
   memcpy(addr, &v, sizeof(v));
}

template<endianness E, typename T>
typename std::enable_if<E != NativeEndianness && sizeof(T) != 1>::type set_primitive(void* addr, T v)
{
   reverse_copy(addr, &v, sizeof(v));
}

char buf[120];

int main()
{
   set_primitive<endianness::little>(buf, '1');
   set_primitive<endianness::little>(buf, 1);
   set_primitive<endianness::big>(buf, '1');
   set_primitive<endianness::big>(buf, 1);
}
```

**Comment by OleksandrKvl** [comment]
that will only cause code duplication without any benefits, existing PR fixes the problem with only a couple of lines.

**Comment by ujos** [comment]
Ok, up to you. 

I will try to verify your change as quickly as possible. I need to switch from Conan to Git repo somehow.

**Comment by ujos** [comment]
>  that will only cause code duplication 

Actually the way as I proposed is better, as it makes code more clear. It removes `IF` statement out of `set_primitive`

**Comment by ujos** [comment]
> Can you please check if the fix from PR works for you? I don't have access to MSVC compiler at the moment.

That works. Thank you very much

**Comment by OleksandrKvl** [comment]
Good, then I'm merging, thank you for reporting and testing the fix!

**Comment by OleksandrKvl** [comment]
@ujos do you want this fix in Conan ASAP? I'm thinking if I should wait till the end of the week, maybe you'll discover more MSVC-related problems.

**Comment by OleksandrKvl** [comment]
Actually, I was wrong about avoidance of `from_unsigned<T>{}(byteswap(to_unsigned(res)));`. Since it's not a `constexpr-if`, this part is always compiled even if never used so there's no space for optimization at all. I will consider further improvements in this area.

**Comment by ujos** [comment]
> @ujos do you want this fix in Conan ASAP? I'm thinking if I should wait till the end of the week, maybe you'll discover more MSVC-related problems.

That was the only issue I found so far. That would be just great to have a release in the Conan next week.

**Comment by OleksandrKvl** [comment]
@ujos you can monitor this [PR](https://github.com/conan-io/conan-center-index/pull/25359) to know when it's available on CCI.
